spring:
  application:
    name: unisew
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres.calidcboamgubysvrdpx
    password: UniSewSU_2025#
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_nationalized_character_data: true
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    locale: vi_VN

google:
  client:
    id: 283612317183-1rhpd52b3duhj1c5kfanadpbb8l0m8nh.apps.googleusercontent.com
    response-type: code
    scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
    access-type: offline
